name:  TÃ¢che Quotidienne

on:
  schedule:
    # Tous les jours Ã  6h du matin
    - cron: '0 6 * * *'

jobs:
  tache-automatique:
    runs-on: ubuntu-latest
    
    steps:
      - name: RÃ©cupÃ©rer le code
        uses: actions/checkout@v4
        
      - name:  Message quotidien
        run: echo " Bonjour ! Il est 6h du matin - TÃ¢che exÃ©cutÃ©e le $(date)"
        
      - name: ðŸ“Š VÃ©rifier l'espace disque
        run: df -h
